### ISSUE TITLE
Hitting GitHub API rate limits

### ISSUE THREAD

**Issue by bbelderbos** [bbelderbos/github-tools#5]
```
$ python -m ghtools --copy-issues --destination pdm-test-repo
...
│ ✅     │ Copied issue Wins - An issue to track small and big wins                                                                                                                  │
│ ❌     │ Cannot create issue, exception: 403 {"message": "You have exceeded a secondary rate limit and have been temporarily blocked from content creation. Please retry your      │
│        │ request again later. If you reach out to GitHub Support for help, please include the request ID D42D:4B2D:2359727:23E5B08:65421474.", "documentation_url":                │
│        │ "https://docs.github.com/rest/overview/resources-in-the-rest-api#secondary-rate-limits"}
...
```

This error happened exactly upon copy action number 30 (after 9 milestones + 20 issues)

**Comment by Zaubeerer** [comment]
Oh, maybe an easy fix is to simply add a sleep timer? :)

**Comment by bbelderbos** [comment]
Yes that would be my first go (simple!), not sure why 30 though unless I ran it twice, then it would match what the docs say:

https://docs.github.com/rest/overview/resources-in-the-rest-api#secondary-rate-limits

> For unauthenticated requests, the rate limit allows for up to 60 requests per hour.

**Comment by Zaubeerer** [comment]
60 per hour is super low 😮

**Comment by bbelderbos** [comment]
Yeah I would need to look into it more, it's a POST not GET action though, but yeah I am less worried now that we're reducing the issue count anyways so I am closing this for now.
